networks:
  db:
    driver: bridge

services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_USER=dbuser'
      - 'MYSQL_PASSWORD=dbpassword'
      - 'MYSQL_DATABASE=forum'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - 'db'