server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: forumhub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: dbuser
    password: dbpassword
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migrations
    validate-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

api:
  server:
    url:
      dev: http://localhost:8080
      prod: http://localhost:8080
  security:
    token:
      secret: ${JWT_SECRET:secret}